# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

matrix:
  include:
  - php: 5.2
    dist: precise
    script: phpunit --strict --configuration phpunit.xml --coverage-text
  - php: 5.3
    dist: precise
    script: phpunit --strict-coverage --strict-global-state --configuration phpunit.xml --coverage-text
  - php: 5.4
    dist: trusty
    script: phpunit --strict-coverage --strict-global-state --configuration phpunit.xml --coverage-text
  - php: 5.5
    dist: trusty
    script: phpunit --strict-coverage --strict-global-state --configuration phpunit.xml --coverage-text
  - php: 5.6
    script: phpunit --strict-coverage --strict-global-state --configuration phpunit.xml --coverage-text

notifications:
  email: false


