# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

matrix:
  include:
  - php: 5.2
    dist: precise
  - php: 5.3
    dist: precise
  - php: 5.4
    dist: trusty
  - php: 5.5
    dist: trusty
  - php: 5.6
  - php: 7.0
  - php: 7.1
  - php: 7.2
  - php: 7.3

notifications:
  email: false

script: phpunit --strict --configuration phpunit.xml --coverage-text

